/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : rgill
 * Created : 10/22/2015 12:54:23
 */

package com.bmj.hackday.locumapp.service;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

import java.util.List;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.SpringApplicationConfiguration;
import org.springframework.context.annotation.Profile;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

import com.bmj.hackday.locumapp.Application;
import com.bmj.hackday.locumapp.model.Candidate;
import com.bmj.hackday.locumapp.model.UserName;

@RunWith(SpringJUnit4ClassRunner.class)
@SpringApplicationConfiguration(classes = Application.class)
@Profile("test")
public class CandidatesServiceTest {

	@Autowired
	private CandidatesService candidatesService;

	/**
	 *
	 * @see com.bmj.hackday.locumapp.service.CandidatesService#getCandidates(UserName)
	 */
	@Test
	public void testGetCandidates_NullOrEmptyName_GivesEmptyList() {
		List<Candidate> candidates = candidatesService.getCandidates(null);
		assertTrue("candidates should be not null and length equal to 0", candidates != null && candidates.size() == 0);
	}
	
	@Test
	public void testGetCandidates_InvalidName_GivesEmptyList() throws Exception {
		UserName username = new UserName();
		username.setName("invalid_name");
		List<Candidate> candidates = candidatesService.getCandidates(username);
		assertTrue("candidates should be not null and length equal to 0", candidates != null && candidates.size() == 0);
	}

	
	@Test
	public void testGetCandidates_HospitalName_GivesListOfDoctors() throws Exception {
		UserName username = new UserName();
		username.setName("hospital");
		List<Candidate> candidates = candidatesService.getCandidates(username);
		assertEquals("Candidates list size does not match", 5, candidates.size());
		
		
	}
}
